# Generated by Django 5.2 on 2025-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorite_dish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Favorite dish'),
        ),
    ]
