# Generated by Django 5.2 on 2025-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_favorite_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorite_dish',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_billing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Last billing amount (₹)'),
        ),
    ]
